source 'http://rubygems.org'

group :development do
  gem 'middleman', '~>3.0.0.beta'
end

group :rack do
  # gem 'rack', '~>1.4.1'
  gem 'rack', '~>1.3.5' # required by middleman
  gem 'rack-rewrite', '~>1.2.1', :require => 'rack/rewrite'
  gem 'rack-contrib', '~>1.1.0', :require => ['rack/contrib/try_static', 'rack/contrib/static_cache']
end
