source "https://rubygems.org"

gem "middleman"
gem "middleman-livereload"
gem "middleman-sprockets"
gem "middleman-syntax"
gem "therubyracer"
gem "oj"
gem "redcarpet"
gem "sass-globbing"
gem "animation"
